---
# See: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Let iptables see bridged traffic.
  copy:
    content: |
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf
  register: module

- name: Let iptables see bridged traffic.
  command: modprobe br_netfilter

- name: Let iptables see bridged traffic.
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
  register: config

- name: Let iptables see bridged traffic.
  command: sysctl --system
  when: config.changed

- name: Disable SWAP partitions
  command: swapoff -a

- name: Remove any swap partition defined in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '\sswap\s'
    state: absent